In [106]:
import numpy as np
from scipy.stats import norm, bernoulli, multivariate_normal

In [488]:
rho = 1e-4
c = 100000

In [489]:
def sample_gammas(gammas_probs):
    return [1 if np.random.rand() < p else 0 for p in gammas_probs]

def var_w(gamma): # variance of w
    assert gamma in [0, 1]
    return rho if gamma == 0 else c * rho

def sample_weights(gammas):
    return [np.random.normal(0, var_w(gamma)) for gamma in gammas]

def gaussian(x, mu, var):
    coef = 1 / np.sqrt(var * 2 * np.pi) 
    exp = np.exp(-0.5 * ((x - mu) ** 2)/var)
    return coef * exp

def prob_w(w, gamma):
    return gaussian(w, 0, var_w(gamma))

def prob_gamma(gamma):
    return rho if gamma == 0 else c * rho

In [490]:
def gamma_post(k, gammas_probs, gammas, ws):
    p0 = (1 - gammas_probs[k]) * prob_w(ws[k], 0)
    p1 = gammas_probs[k] * prob_w(ws[k], 1)
    return p1 / (p0 + p1)

def w_post(X, y, gammas, noise): # p(w | stuff)
    diag = [1 / ((c ** gamma) * rho) for gamma in gammas]
    R_gamma_inv = np.diag(diag)
    xtx = X.T @ X
    mean = np.linalg.inv(noise * R_gamma_inv + xtx) @ X.T @ y
    var = np.linalg.inv(R_gamma_inv + xtx / noise)

    return np.random.multivariate_normal(mean, var)

In [491]:
def gibbs(X, y, n, noise):
    gammas_probs = np.repeat(0.5, X.shape[1])
    gammas = sample_gammas(gammas_probs)
    ws = w_post(X, y, gammas, noise)
    
    integral = np.zeros(X.shape[1])
    for i in range(n):
        ws = w_post(X, y, gammas, noise)
        for i in range(len(gammas_probs)):
            gammas_probs[i] = gamma_post(i, gammas_probs, gammas, ws)
        gammas = sample_gammas(gammas_probs)
        
        w_probs = np.zeros(X.shape[1])
        gamma_prior = np.zeros(X.shape[1])
        for i in range(len(w_probs)):
            w_probs[i] = prob_w(ws[i], gammas[i])
            gamma_prior[i] = prob_gamma(gammas[i])
            
        integral += ws * gammas * w_probs * gammas_probs
    return ws, gammas, integral

In [497]:
d = 100
s = 5
n = 1000
noise = 0.1
X = np.random.uniform(size=(n, d))
ws = np.zeros(d)
indices = np.arange(d)
np.random.shuffle(indices)
ws[indices[:s]] = 1
print(ws)
y = np.dot(X, ws) + np.random.normal(0, noise)

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [521]:
runs = 100
ws, gammas, integral = gibbs(X, y, runs, noise)
ws[indices[:s]]

array([1.00019966, 1.02427643, 0.9976252 , 1.06340773, 0.98652045])

In [522]:
(integral / runs)

array([ 0.00000000e+00,  0.00000000e+00,  6.26286782e-05,  3.92073334e-06,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        1.20619881e-01,  4.61280150e-04,  0.00000000e+00,  6.13271579e-05,
        3.20609084e-04,  0.00000000e+00,  1.28466618e-04,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  2.42412480e-04,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        1.18703921e-01,  1.12791863e-03,  0.00000000e+00,  1.11579330e-03,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  7.12488273e-04,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  7.62695500e-04,
        0.00000000e+00,  5.11204535e-04,  0.00000000e+00,  7.76228087e-05,
        1.19147522e-01,  1.20951197e-01,  4.56048123e-05,  4.45299141e-04,
        1.19289483e-03,  4.49513272e-04,  0.00000000e+00,  0.00000000e+00,
        4.85858543e-05,  0.00000000e+00,  0.00000000e+00, -4.82102530e-05,
        1.18948433e-01,  

In [523]:
np.array(gammas)[indices[:s]]

array([1, 1, 1, 1, 1])

In [524]:
np.multiply(ws, gammas)[indices[:s]]

array([1.00019966, 1.02427643, 0.9976252 , 1.06340773, 0.98652045])